CREATE TABLE "books" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "author_id" bigint,
  "genre_id" bigint,
  "price" decimal(10,2) NOT NULL,
  "available" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "authors" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "bio" text
);

CREATE TABLE "genres" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE INDEX ON "books" ("title");

CREATE INDEX ON "books" ("author_id");

CREATE INDEX ON "books" ("genre_id");

CREATE INDEX ON "books" ("created_at");

CREATE INDEX ON "authors" ("name");

CREATE INDEX ON "genres" ("name");

ALTER TABLE "books" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("id");

ALTER TABLE "books" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");
