CREATE TABLE "books" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "author_id" bigint NOT NULL,
  "genre_id" bigint NOT NULL,
  "price" bigint NOT NULL,
  "available" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL UNIQUE,
  "password_hash" varchar NOT NULL,
  "email" varchar NOT NULL UNIQUE,
  "token" varchar,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "authors" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "bio" text NOT NULL
);

CREATE TABLE "genres" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE INDEX ON "books" ("title");

CREATE INDEX ON "books" ("author_id");

CREATE INDEX ON "books" ("genre_id");

CREATE INDEX ON "books" ("created_at");

CREATE INDEX ON "authors" ("name");

CREATE INDEX ON "genres" ("name");

CREATE INDEX ON "users" ("username");

CREATE INDEX ON "users" ("email");

ALTER TABLE "books" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("id");

ALTER TABLE "books" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");
