// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Author struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Bio  string `json:"bio"`
}

type Book struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	AuthorID  int64     `json:"author_id"`
	GenreID   int64     `json:"genre_id"`
	Price     int64     `json:"price"`
	Available bool      `json:"available"`
	CreatedAt time.Time `json:"created_at"`
}

type Genre struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        string         `json:"email"`
	Token        sql.NullString `json:"token"`
	CreatedAt    time.Time      `json:"created_at"`
}
